name: Build Sample NuGet Package Project

on:
  push:
    tags: v*

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  RELEASE_VERSION: ${GITHUB_REF#refs/tags/v}

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Pack Project
      run: dotnet pack --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ env.RELEASE_VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
    - name: Push Package
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
